name: Premium Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake (Dark + Light)
        uses: Platane/snk@v3
        with:
          github_user_name: nhebotx-md
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=00f7ff
            dist/github-contribution-grid-snake-light.svg?palette=github-light&color_snake=00f7ff

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
